name:                sandbox
version:             0.1.0.0
github:              "goedestudent/uu-thesis"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
# - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/goedestudent/uu-thesis#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
# - -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -debug

library:
  source-dirs: src
  dependencies:
    - accelerate
    - accelerate-llvm
    - accelerate-llvm-native
    - accelerate-llvm-ptx
    - accelerate-io-JuicyPixels
    - JuicyPixels
    - llvm-hs==9.0.*
    - llvm-hs-pure

executables:
  sandbox-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - sandbox
    - time
    - accelerate
    - accelerate-llvm
    - accelerate-llvm-ptx

benchmarks:
  sandbox-bench:
    main:                Spec.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    - -fno-full-laziness
    dependencies:
    - sandbox
    - criterion
    - accelerate
    - accelerate-llvm
    - accelerate-llvm-ptx